"""empty message

Revision ID: 89f03d39704f
Revises: 80107c3ad6b8
Create Date: 2017-09-25 15:38:15.628043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89f03d39704f'
down_revision = '80107c3ad6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resourcelists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('EmpNumber', sa.String(length=255), nullable=True),
    sa.Column('Designation', sa.String(length=255), nullable=True),
    sa.Column('EmployeeType', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('PSFT_ID', sa.Integer(), nullable=True),
    sa.Column('Date_of_joining', sa.DateTime(), nullable=True),
    sa.Column('TEK_Experience', sa.Float(), nullable=True),
    sa.Column('Past_Experience', sa.Float(), nullable=True),
    sa.Column('Total_Experience', sa.Float(), nullable=True),
    sa.Column('Family', sa.String(length=255), nullable=True),
    sa.Column('Manager', sa.String(length=255), nullable=True),
    sa.Column('Reporting_Manager', sa.String(length=255), nullable=True),
    sa.Column('Level_1_Manager', sa.String(length=255), nullable=True),
    sa.Column('Project', sa.String(length=255), nullable=True),
    sa.Column('Billable', sa.String(length=255), nullable=True),
    sa.Column('Organization', sa.String(length=255), nullable=True),
    sa.Column('Primary_Skill', sa.String(length=255), nullable=True),
    sa.Column('Customer', sa.String(length=255), nullable=True),
    sa.Column('Sales_Manager', sa.String(length=255), nullable=True),
    sa.Column('Delivery_manager', sa.String(length=255), nullable=True),
    sa.Column('PMO_Owner', sa.String(length=255), nullable=True),
    sa.Column('TEK_Systems_Bucket', sa.String(length=255), nullable=True),
    sa.Column('Overall_Bucket', sa.String(length=255), nullable=True),
    sa.Column('Offshore_DM', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bucketlists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bucketlists_pkey')
    )
    op.drop_table('resourcelists')
    # ### end Alembic commands ###
